spring:
  kafka:
    consumer:
      group-id: demo-processor
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        demo-request:
          destination: demoRequest
          group: demo-gateway
          consumer:
            partitioned: true
        demo-response:
          destination: demoResponse
          group: demo-gateway
          consumer:
            partitioned: true
      instance-count: 3
      instance-index: 0