spring:
  kafka:
    consumer:
      group-id: demo-processor
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        input:
          destination: demoRequest
          group: demo-gateway
          consumer:
            partitioned: true
        output:
          destination: demoResponse
          group: demo-gateway
          producer:
            partition-key-expression: headers['response-partition-key']
      instance-count: 3
      instance-index: 0